@startuml gestionDesBien
left to right direction
actor Admin as a
actor Guest as g

package Les_Biens {
  usecase "Visualiser" as vlb
  usecase "Authentification" as auth
  usecase "Supprimer" as del
  usecase "Ajouter" as add
  usecase "Editer" as edit
    del ..> auth : <<include>>
    add ..> auth : <<include>>
    edit ..> auth : <<include>>
}

a --> add
a --> edit
a --> del
a --> auth
g --> vlb
g<|-a

@enduml
